"""
llm.py — Ollama call with schema-constrained JSON output.

Design:
  * The output schema is a Pydantic model; its JSON schema is passed as Ollama
    `format`, so decoding is grammar-constrained (no free-form JSON parsing).
  * `src` is an enum built per request: "report", "inferred", or "kb:<id>" for
    exactly the chunks retrieved for this report — the model cannot cite a
    source that was not in its context.
  * `metrics` are NOT generated by the LLM: they are rendered deterministically
    from the rule-based abnormal findings (zero numeric hallucination).
  * v4 (latency): when the rule engine covers lab-derived conditions/risks
    (conditions.py; `rules_cover_labs=True`, the pipeline default) the model
    no longer re-generates them. It outputs only what rules cannot: a short
    summary, advice, and conditions that are *stated in the report text*
    (imaging / physical-exam findings, e.g. 脂肪肝). Decoding is ~95% of the
    LLM time (prefill ~2,000 tok/s vs decode ~43 tok/s on an RTX 4060), so
    output tokens are what matter.
  * num_ctx is set explicitly and is the SAME for every qwen call (generator,
    judge, rewrite) — Ollama reloads a model when num_ctx changes.
"""

import json
import re
import unicodedata
from typing import Callable, Dict, List, Optional, Tuple

import requests
from pydantic import BaseModel, Field, ValidationError

import config

PROMPT_VERSION = "v4-advice-textcond"

CATEGORY_KEYS = [
    "conditions", "risks", "metrics", "lifestyle",
    "food", "exercise", "supplements", "avoid",
]
ADVICE_KEYS = ["lifestyle", "food", "exercise", "supplements", "avoid"]
# legacy schema (rules_cover_labs=False): the model also produces conditions/risks
LLM_CATEGORY_KEYS = ["conditions", "risks", *ADVICE_KEYS]
MAX_TAGS_PER_CATEGORY = 4
TAG_MAX_CHARS = 24        # grammar cap; the prompt asks for 2–12 字
SUMMARY_MAX_CHARS = 80    # grammar cap; the prompt asks for <= 60 字
TEXT_CONDITIONS_KEY = "text_conditions"

_TAG_RULES = """- 只輸出符合 schema 的 JSON。所有文字一律使用繁體中文（台灣用語）。
- 每個標籤是物件 {"text": 2–12 字的短標籤（不是句子）, "src": 來源}。
  • src="report"：報告原文或「異常檢驗值」清單直接支持。
  • src="kb:<id>"：由該 id 的參考資料片段直接支持（只能使用 schema 允許的 id）。
  • src="inferred"：臨床上顯而易見的推論，盡量少用。"""

_ADVICE_RULES = f"""- lifestyle / food / exercise / supplements / avoid：針對「這位受檢者的異常項目」的具體建議，優先引用 kb:<id>；避免與異常無關的空泛建議。
- 寧缺勿濫：每類最多 {MAX_TAGS_PER_CATEGORY} 個，品質優先。"""

SYSTEM_PROMPT = f"""你是健康檢查報告的標籤助理。閱讀一份繁體中文健檢報告、由程式計算出的異常檢驗值與規則判定的狀況，以及參考資料片段，輸出少量「有依據」的標籤。

# 規則
{_TAG_RULES}
- 由檢驗數值推得的狀況與風險（例：血脂異常、心血管疾病風險）已由程式判定，不要輸出。
- text_conditions：逐行檢查「報告中的文字結論段落」（影像如超音波、X 光、攝影，心電圖、理學檢查、醫師結論），列出其中明寫的每一個異常發現或診斷，使用報告原用語並含部位（例：「輕度脂肪肝」、「膽囊瘜肉」、「心律不整」、「甲狀腺結節」）。每項 {{"text": 報告原用語}}。
  • 只列這類文字發現；「規則判定的狀況」與「異常檢驗值」已由程式處理，不要重複（例：血脂異常、肥胖、貧血）。
  • 寫「正常」「無明顯異常」者不列；沒有這類發現就輸出空陣列，不可捏造。
{_ADVICE_RULES}
- 若所有檢驗值都正常，text_conditions 留空，建議類只給少量一般性保健建議。
- summary：一句白話摘要，60 字以內。"""

# Used when no rule engine runs (use_rules=False ablation, legacy app.py).
SYSTEM_PROMPT_LEGACY = f"""你是健康檢查報告的標籤助理。閱讀一份繁體中文健檢報告、由程式計算出的異常檢驗值，以及參考資料片段，輸出少量「有依據」的標籤。

# 規則
{_TAG_RULES}
- conditions：報告明寫的診斷，或由異常值直接支持的狀況（例：高血脂、脂肪肝）。不可捏造。
- risks：由異常值合理推得的未來風險（例：心血管疾病風險）。
{_ADVICE_RULES}
- 若所有檢驗值都正常，conditions 與 risks 請留空，建議類只給少量一般性保健建議。
- summary：一句白話摘要，60 字以內。"""


# ─── Output schema ───────────────────────────────────────────────────────────

class Tag(BaseModel):
    text: str = Field(min_length=1, max_length=40)
    src: str


class CondTag(BaseModel):
    text: str = Field(min_length=1, max_length=40)


# `conf` is no longer generated: at temperature 0 qwen2.5:7b wrote conf=1.0 for
# every tag (no information) at ~7 output tokens per tag (~30% of the output).
# It is now a deterministic prior by source, decreasing slightly with the
# position the model listed the tag in (the model lists its best tags first;
# verify.py's inferred-share cap drops the lowest conf first).
SRC_CONF = {"report": 0.9, "kb": 0.8, "inferred": 0.6}


def prior_conf(src: str, position: int = 0) -> float:
    base = SRC_CONF["kb"] if src.startswith("kb:") else SRC_CONF.get(src, SRC_CONF["inferred"])
    return round(max(0.3, base - 0.02 * position), 2)


class LLMTags(BaseModel):
    """v4: advice + text-stated conditions (rules cover lab-derived ones)."""
    summary: str
    text_conditions: List[CondTag]
    lifestyle: List[Tag]
    food: List[Tag]
    exercise: List[Tag]
    supplements: List[Tag]
    avoid: List[Tag]


class LLMTagsLegacy(BaseModel):
    summary: str
    conditions: List[Tag]
    risks: List[Tag]
    lifestyle: List[Tag]
    food: List[Tag]
    exercise: List[Tag]
    supplements: List[Tag]
    avoid: List[Tag]


def schema_keys(rules_cover_labs: bool = True) -> List[str]:
    """Array properties of the output schema, in generation order."""
    return [TEXT_CONDITIONS_KEY, *ADVICE_KEYS] if rules_cover_labs else list(LLM_CATEGORY_KEYS)


def build_output_schema(allowed_src: List[str], rules_cover_labs: bool = True) -> dict:
    """JSON schema for Ollama `format`, with src restricted to allowed values."""
    text = {"type": "string", "maxLength": TAG_MAX_CHARS}
    tag = {"type": "object",
           "properties": {"text": text, "src": {"type": "string", "enum": allowed_src}},
           "required": ["text", "src"]}
    cond = {"type": "object", "properties": {"text": text}, "required": ["text"]}
    props = {"summary": {"type": "string", "maxLength": SUMMARY_MAX_CHARS}}
    for k in schema_keys(rules_cover_labs):
        props[k] = {"type": "array", "items": cond if k == TEXT_CONDITIONS_KEY else tag,
                    "maxItems": MAX_TAGS_PER_CATEGORY}
    return {"type": "object", "properties": props, "required": ["summary", *schema_keys(rules_cover_labs)]}


def allowed_sources(chunk_ids: List[str]) -> List[str]:
    return ["report", "inferred"] + [f"kb:{cid}" for cid in chunk_ids]


# ─── Deterministic metrics ───────────────────────────────────────────────────

def metrics_from_findings(findings: List[Dict]) -> List[Dict]:
    """Render abnormal findings as metric tags — no LLM involved."""
    out = []
    for f in findings:
        arrow = {"high": "↑", "low": "↓"}.get(f.get("direction"))
        if not arrow:
            continue
        value = f["value"]
        value_s = f"{value:g}" if isinstance(value, float) else str(value)
        unit = f" {f['unit']}" if f.get("unit") else ""
        out.append({"text": f"{f['name']} {value_s}{unit} {arrow}", "src": "report", "conf": 1.0})
    return out


# ─── Prompt ──────────────────────────────────────────────────────────────────

# Lines worth pointing the model at for text-stated conditions.
_NARRATIVE = re.compile(r"超音波|X\s*光|攝影|心電圖|理學|結論|診斷|發現|內視鏡|胃鏡|大腸鏡|骨密度|眼底|"
                        r"聽力|視力|斷層|CT|MRI|檢查結果|醫師|印象|Impression", re.I)
_HEADER_ROW = re.compile(r"^\s*(?:項目|檢查項目|檢驗項目)\s+(?:結果|檢驗結果|數值)(?:\s+\S+){0,3}\s*$")
_NOISE = re.compile(r"[\s\d.,:：;；/\\()\[\]（）<>≦≧≤≥=+\-~～↑↓*＊%|A-Za-zµμγαβ^]+")


def _nk(s: str) -> str:
    return unicodedata.normalize("NFKC", s or "").lower()


def strip_lab_lines(text: str, findings: Optional[List[Dict]]) -> Tuple[str, int]:
    """Drop report lines that are pure lab-value rows already parsed into
    `findings` (their abnormal ones are listed in the findings block), plus
    bare table header rows. Narrative lines (醫師建議, 影像結論, 理學檢查 …)
    are kept: a line is dropped only when, after removing the item name,
    value, unit and range, at most 4 CJK characters remain."""
    if not findings:
        return text, 0
    keys = []
    for f in findings:
        name, val = _nk(f.get("raw_name") or f.get("name") or ""), _nk(str(f.get("value_text") or ""))
        if name and val:
            keys.append((name, val.split()[0], [_nk(x) for x in (f.get("unit"), f.get("report_range")) if x]))
    out, dropped = [], 0
    for line in text.splitlines():
        nl = _nk(line)
        if _HEADER_ROW.match(nl):
            dropped += 1
            continue
        hit = next((k for k in keys if k[0] in nl and k[1] in nl), None)
        if hit:
            rest = nl.replace(hit[0], " ").replace(hit[1], " ")
            for x in hit[2]:
                rest = rest.replace(x, " ")
            rest = re.sub(r"(男|女|性|正常|陰性|陽性|參考|範圍|單位|次/分|異常|偏高|偏低)", " ", rest)
            if len(_NOISE.sub("", rest)) <= 4:
                dropped += 1
                continue
        out.append(line)
    return "\n".join(out), dropped


def _finding_names(findings: Optional[List[Dict]]) -> List[str]:
    names = set()
    for f in findings or []:
        for k in ("display_name", "matched_name", "raw_name", "name"):
            n = _nk(f.get(k) or "").strip()
            if len(n) >= 2:
                names.add(n)
    return sorted(names)


def _bigram_support(tag: str, body: str) -> float:
    s = re.sub(r"\W+", "", tag)
    grams = {s[i:i + 2] for i in range(len(s) - 1)} or ({s} if s else set())
    return sum(g in body for g in grams) / len(grams) if grams else 0.0


def filter_text_conditions(conds: List[Dict], text: str, findings: Optional[List[Dict]]) -> List[Dict]:
    """Keep only text-stated conditions: the tag must be supported by the
    report's non-lab text and must not name a lab item (those are the rule
    engine's job). Measured on syn_048: the model otherwise echoed lab
    findings such as "腎絲球過濾率 27.7" as conditions."""
    if not conds:
        return conds
    body = re.sub(r"\W+", "", _nk(strip_lab_lines(text, findings)[0]))
    names = _finding_names(findings)
    out = []
    for c in conds:
        t = _nk(c["text"])
        core = re.sub(r"[\d.]+\s*(?:cm|mm|公分|毫米)?|[（(][^）)]*[）)]|\W+", "", t)
        if any(n in t for n in names):
            continue
        if core and (core in body or _bigram_support(core, body) >= 0.75):
            out.append(c)
    return out


def build_user_message(text: str, findings_text: str, context: str,
                       max_chars: int = config.REPORT_MAX_CHARS,
                       context_max_chars: int = config.CONTEXT_MAX_CHARS,
                       findings: Optional[List[Dict]] = None, rules_cover_labs: bool = False) -> str:
    """findings: when given, lab-value rows already parsed into findings are
    removed from the report text (strip_lab_lines) — saves prompt tokens and
    leaves more of the REPORT_MAX_CHARS budget for narrative text."""
    note = ""
    if findings:
        text, n = strip_lab_lines(text, findings)
        if n:
            note = f"\n[已移除 {n} 行檢驗數值表格列：共 {len(findings)} 項檢驗值已由程式解析，異常者列於下方「異常檢驗值」]"
    report = text[:max_chars]
    if len(text) > max_chars:
        report += f"\n[…報告其餘內容已截斷（原長 {len(text)} 字）]"
    parts = [f"# 健檢報告（原文擷取）\n\n{report}{note}"]
    if rules_cover_labs:
        # Measured: without this section qwen2.5:7b echoed the rule conditions
        # into text_conditions and missed imaging findings.
        lines = [ln.strip() for ln in report.splitlines() if _NARRATIVE.search(ln)]
        parts.append("\n\n---\n# 報告中的文字結論段落（text_conditions 只從這裡找）\n"
                     + ("\n".join(lines) if lines else "（無）"))
    parts.append(
        "\n\n---\n# 異常檢驗值（程式依參考範圍計算，屬客觀事實）\n"
        + (findings_text or "（無異常值）")
    )
    if context:
        parts.append(
            "\n\n---\n# 參考資料片段（每段開頭 [id]，可用 src=\"kb:<id>\" 引用）\n\n"
            + context[:context_max_chars]
        )
    parts.append("\n\n---\n請輸出 JSON。")
    return "\n".join(parts)


# ─── Call ────────────────────────────────────────────────────────────────────

def llm_options(num_predict: int = config.LLM_NUM_PREDICT, seed: int = 42) -> dict:
    """Options for every qwen chat call. num_ctx must be identical across the
    generator / judge / rewrite calls or Ollama reloads the model (~9 s)."""
    return {"temperature": config.LLM_TEMPERATURE, "num_ctx": config.LLM_NUM_CTX,
            "num_predict": num_predict, "seed": seed}


def _chat(payload: dict, base_url: str) -> Tuple[Optional[dict], str]:
    try:
        resp = requests.post(f"{base_url}/api/chat", json=payload, timeout=config.LLM_TIMEOUT_S)
        resp.raise_for_status()
        return resp.json(), ""
    except requests.exceptions.ConnectionError:
        return None, f"Cannot connect to Ollama at {base_url}. Is Ollama running? Try: ollama serve"
    except requests.exceptions.Timeout:
        return None, f"Request timed out after {config.LLM_TIMEOUT_S}s."
    except requests.exceptions.HTTPError as e:
        body = getattr(e.response, "text", "")[:300]
        return None, f"Ollama HTTP error: {e} {body}"


def _chat_stream(payload: dict, base_url: str, on_text: Callable[[str], None]) -> Tuple[Optional[dict], str]:
    """Streamed /api/chat (works together with `format` on Ollama 0.33.1).
    Calls on_text(accumulated_text) per chunk; returns the final chunk with
    message.content = full text (same shape as the non-streamed response)."""
    buf: List[str] = []
    try:
        with requests.post(f"{base_url}/api/chat", json={**payload, "stream": True},
                           timeout=config.LLM_TIMEOUT_S, stream=True) as resp:
            resp.raise_for_status()
            final: dict = {}
            for line in resp.iter_lines():
                if not line:
                    continue
                j = json.loads(line)
                if j.get("error"):
                    return None, f"Ollama error: {j['error']}"
                piece = (j.get("message") or {}).get("content", "")
                if piece:
                    buf.append(piece)
                    try:
                        on_text("".join(buf))
                    except Exception:  # noqa: BLE001 — a UI callback must never break generation
                        pass
                if j.get("done"):
                    final = j
                    break
        final["message"] = {"role": "assistant", "content": "".join(buf)}
        return final, ""
    except requests.exceptions.ConnectionError:
        return None, f"Cannot connect to Ollama at {base_url}. Is Ollama running? Try: ollama serve"
    except requests.exceptions.Timeout:
        return None, f"Request timed out after {config.LLM_TIMEOUT_S}s."
    except requests.exceptions.HTTPError as e:
        body = getattr(e.response, "text", "")[:300]
        return None, f"Ollama HTTP error: {e} {body}"
    except ValueError as e:
        return None, f"Bad stream from Ollama: {e}"


def call_stats(data: dict) -> Dict:
    """Ollama timing fields -> seconds / tokens (prefill vs decode vs load)."""
    ns = 1e9
    return {"prompt_tokens": data.get("prompt_eval_count"), "out_tokens": data.get("eval_count"),
            "load_s": round((data.get("load_duration") or 0) / ns, 3),
            "prefill_s": round((data.get("prompt_eval_duration") or 0) / ns, 3),
            "decode_s": round((data.get("eval_duration") or 0) / ns, 3)}


def analyze_report(
    text: str,
    context: str = "",
    findings_text: str = "",
    tables_md: str = "",  # kept for API compatibility; tables are already in `text`
    model: str = config.LLM_MODEL,
    base_url: str = config.OLLAMA_BASE_URL,
    max_chars: int = config.REPORT_MAX_CHARS,
    chunk_ids: Optional[List[str]] = None,
    findings: Optional[List[Dict]] = None,
    retries: int = 1,
    rules_cover_labs: bool = False,
    on_text: Optional[Callable[[str], None]] = None,
) -> Tuple[dict, str]:
    """Return (result_dict, error_string).

    result keys: summary + 8 categories; each tag is {text, src, conf} (conf =
    prior_conf by source, not generated); plus
    `_llm` (token counts and prefill/decode/load seconds of the last call).
    `chunk_ids` are the retrieved chunk ids the model may cite.
    `findings` (from abnormal.evaluate_findings) populate `metrics`
    deterministically and let the prompt drop lab rows already parsed.
    rules_cover_labs: the caller merges rule-derived conditions/risks
    (conditions.py), so the model outputs only advice + text-stated
    conditions (`risks` is then empty here). False = legacy schema.
    on_text: stream the output; called with the accumulated raw JSON text
    (see partial_tags) — for progressive UI rendering.
    """
    allowed = allowed_sources(chunk_ids or [])
    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT if rules_cover_labs else SYSTEM_PROMPT_LEGACY},
            {"role": "user", "content": build_user_message(text, findings_text, context, max_chars,
                                                           findings=findings,
                                                           rules_cover_labs=rules_cover_labs)},
        ],
        "stream": False,
        "format": build_output_schema(allowed, rules_cover_labs),
        "keep_alive": config.OLLAMA_KEEP_ALIVE,
        "options": llm_options(),
    }
    model_cls = LLMTags if rules_cover_labs else LLMTagsLegacy

    last_err = ""
    for _attempt in range(retries + 1):
        data, err = _chat_stream(payload, base_url, on_text) if on_text else _chat(payload, base_url)
        if err:
            last_err = err
            continue
        raw = (data.get("message") or {}).get("content", "")
        if data.get("done_reason") == "length":
            last_err = f"Output hit num_predict={config.LLM_NUM_PREDICT} and was cut off"
            continue
        try:
            parsed = model_cls.model_validate_json(raw)
        except ValidationError as e:
            last_err = f"LLM output failed schema validation: {e.errors()[:2]}\n\nRaw output:\n{raw[:500]}"
            continue
        result = _to_result(parsed, set(allowed))
        if rules_cover_labs:
            result["conditions"] = filter_text_conditions(result["conditions"], text, findings)
        result["metrics"] = metrics_from_findings(findings or [])
        result["_llm"] = call_stats(data)
        return result, ""
    return {}, last_err


def _clean_tags(items, allowed: Optional[set], default_src: Optional[str] = None) -> List[dict]:
    seen, tags = set(), []
    for t in items:
        text = t.text.strip()
        src = default_src or getattr(t, "src", "")
        if not text or text in seen or (allowed is not None and src not in allowed):
            continue
        seen.add(text)
        tags.append({"text": text, "src": src, "conf": prior_conf(src, len(tags))})
    return tags[:MAX_TAGS_PER_CATEGORY]


def _to_result(parsed, allowed: set) -> dict:
    out = {"summary": parsed.summary.strip()}
    if isinstance(parsed, LLMTags):
        # text-stated conditions are claims about the report -> src="report" (verify checks them)
        out["conditions"] = _clean_tags(parsed.text_conditions, None, default_src="report")
        out["risks"] = []
    for key in (ADVICE_KEYS if isinstance(parsed, LLMTags) else LLM_CATEGORY_KEYS):
        out[key] = _clean_tags(getattr(parsed, key), allowed)
    return out


# ─── Streaming helpers ───────────────────────────────────────────────────────

_OBJ = re.compile(r"\{[^{}\[\]]*\}")


def partial_tags(raw: str) -> Dict:
    """Best-effort view of a partially generated output: the summary text so
    far and every *completed* tag object per category. Never raises."""
    out: Dict = {}
    m = re.search(r'"summary"\s*:\s*"((?:[^"\\]|\\.)*)("?)', raw)
    if m:
        try:
            out["summary"] = json.loads(f'"{m.group(1)}"')
        except ValueError:
            out["summary"] = m.group(1)
        out["_summary_done"] = bool(m.group(2))
    keys = [TEXT_CONDITIONS_KEY, *LLM_CATEGORY_KEYS]
    spans = sorted((m.start(), k) for k in keys for m in [re.search(rf'"{k}"\s*:\s*\[', raw)] if m)
    for i, (start, k) in enumerate(spans):
        end = spans[i + 1][0] if i + 1 < len(spans) else len(raw)
        tags = []
        for o in _OBJ.findall(raw[start:end]):
            try:
                t = json.loads(o)
            except ValueError:
                continue
            if isinstance(t, dict) and str(t.get("text", "")).strip():
                src = str(t.get("src", "report"))
                tags.append({"text": t["text"].strip(), "src": src, "conf": prior_conf(src, len(tags))})
        out["conditions" if k == TEXT_CONDITIONS_KEY else k] = tags
    return out


def warmup(model: str = config.LLM_MODEL, base_url: str = config.OLLAMA_BASE_URL) -> str:
    """Load the model with the generator's num_ctx (so the first real call does
    not pay the ~9 s load, and no later call reloads). Returns '' or an error."""
    try:
        r = requests.post(f"{base_url}/api/generate",
                          json={"model": model, "prompt": "", "keep_alive": config.OLLAMA_KEEP_ALIVE,
                                "options": {"num_ctx": config.LLM_NUM_CTX}},
                          timeout=config.LLM_TIMEOUT_S)
        r.raise_for_status()
        return ""
    except Exception as e:  # noqa: BLE001
        return str(e)


def tag_texts(tags: List[dict]) -> List[str]:
    """Convenience: extract just the text strings (for CSV/JSON export)."""
    return [t["text"] for t in tags if t.get("text")]


def _parse_json(text: str) -> Tuple[dict, str]:
    """Lenient JSON parse — kept for callers outside the constrained path."""
    try:
        return json.loads(text), ""
    except json.JSONDecodeError as e:
        return {}, str(e)
